export const SEED_COUNTRIES = [
  { name: "Switzerland", code: "CH" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Croatia", code: "HR" },
  { name: "Slovenia", code: "SI" },
  { name: "Greece", code: "GR" },
  { name: "Bulgaria", code: "BG" },
  { name: "Romania", code: "RO" },
  { name: "Hungary", code: "HU" },
  { name: "Austria", code: "AT" },
  { name: "France", code: "FR" },
  { name: "Spain", code: "ES" },
  { name: "Poland", code: "PL" },
  { name: "Netherlands", code: "NL" },
  { name: "Belgium", code: "BE" },
];

export const SEED_CITIES = [
  ["Belsh", "AL"], ["Berat", "AL"], ["Cërrik", "AL"], ["Durrës", "AL"],
  ["Elbasan", "AL"], ["Fier", "AL"], ["Gjirokastër", "AL"], ["Gramsh", "AL"],
  ["Himarë", "AL"], ["Kamëz", "AL"], ["Kavajë", "AL"], ["Korçë", "AL"],
  ["Krujë", "AL"], ["Fushë-Krujë", "AL"], ["Kukës", "AL"], ["Laç", "AL"],
  ["Lezhë", "AL"], ["Lushnjë", "AL"], ["Pogradec", "AL"], ["Sarandë", "AL"],
  ["Shkodër", "AL"], ["Tirana", "AL"], ["Vlorë", "AL"], ["Peshkopi", "AL"],
  ["Burrel", "AL"], ["Ballsh", "AL"], ["Kuçovë", "AL"], ["Patos", "AL"],

  ["Prishtina", "XK"], ["Prizren", "XK"], ["Peja", "XK"], ["Gjakova", "XK"],
  ["Gjilan", "XK"], ["Ferizaj", "XK"], ["Mitrovica", "XK"], ["Podujeva", "XK"],
  ["Vushtrri", "XK"], ["Suhareka", "XK"], ["Rahovec", "XK"], ["Malisheva", "XK"],
  ["Lipjan", "XK"], ["Drenas", "XK"], ["Skenderaj", "XK"], ["Istog", "XK"],
  ["Klinë", "XK"], ["Deçan", "XK"], ["Dragash", "XK"], ["Kaçanik", "XK"],
  ["Shtime", "XK"], ["Fushë Kosovë", "XK"], ["Vitia", "XK"], ["Kamenica", "XK"],

  ["Skopje", "MK"], ["Tetovo", "MK"], ["Gostivar", "MK"], ["Bitola", "MK"],
  ["Kumanovo", "MK"], ["Prilep", "MK"], ["Veles", "MK"], ["Shtip", "MK"],
  ["Ohrid", "MK"], ["Struga", "MK"], ["Strumica", "MK"], ["Kavadarci", "MK"],
  ["Kocani", "MK"], ["Kicevo", "MK"], ["Debar", "MK"], ["Resen", "MK"],
  ["Gevgelija", "MK"], ["Kriva Palanka", "MK"],

  ["Belgrade", "RS"], ["Novi Sad", "RS"], ["Niš", "RS"], ["Kragujevac", "RS"],
  ["Subotica", "RS"], ["Novi Pazar", "RS"], ["Čačak", "RS"], ["Kraljevo", "RS"],
  ["Podgorica", "ME"], ["Nikšić", "ME"], ["Bar", "ME"], ["Budva", "ME"],
  ["Herceg Novi", "ME"], ["Ulcinj", "ME"], ["Kotor", "ME"],
  ["Sarajevo", "BA"], ["Banja Luka", "BA"], ["Mostar", "BA"], ["Tuzla", "BA"],
  ["Zenica", "BA"], ["Zagreb", "HR"], ["Split", "HR"], ["Rijeka", "HR"],
  ["Osijek", "HR"], ["Dubrovnik", "HR"], ["Zadar", "HR"],
  ["Ljubljana", "SI"], ["Maribor", "SI"], ["Koper", "SI"],
  ["Athens", "GR"], ["Thessaloniki", "GR"], ["Patras", "GR"],
  ["Sofia", "BG"], ["Plovdiv", "BG"], ["Varna", "BG"],
  ["Bucharest", "RO"], ["Cluj-Napoca", "RO"], ["Timișoara", "RO"],
  ["Budapest", "HU"], ["Vienna", "AT"], ["Graz", "AT"], ["Salzburg", "AT"],
  ["Berlin", "DE"], ["München", "DE"], ["Hamburg", "DE"], ["Köln", "DE"],
  ["Frankfurt am Main", "DE"], ["Stuttgart", "DE"], ["Düsseldorf", "DE"],
  ["Dortmund", "DE"], ["Leipzig", "DE"], ["Hannover", "DE"], ["Nürnberg", "DE"],
  ["Rome", "IT"], ["Milan", "IT"], ["Naples", "IT"], ["Turin", "IT"],
  ["Bologna", "IT"], ["Florence", "IT"], ["Venice", "IT"],
  ["Zürich", "CH"], ["Geneva", "CH"], ["Basel", "CH"], ["Bern", "CH"],
  ["Lausanne", "CH"], ["Lugano", "CH"], ["Winterthur", "CH"], ["Lucerne", "CH"],
  ["London", "UK"], ["Manchester", "UK"], ["Birmingham", "UK"],
  ["Paris", "FR"], ["Lyon", "FR"], ["Marseille", "FR"],
  ["Madrid", "ES"], ["Barcelona", "ES"],
  ["Amsterdam", "NL"], ["Rotterdam", "NL"],
  ["Brussels", "BE"], ["Antwerp", "BE"],
  ["Warsaw", "PL"], ["Kraków", "PL"],
];
